// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-4)
// protocol is simulatable under MLWE(42,29,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(18,340,2^(43.854807))
// 
// Ring
// degree d = 64
// modulus q = 147573952589676414101, log(q) ~ 67.0
// factors q = q1
// 
// Compression
// D = 20
// gamma = 462322900, log(gamma) ~ 28.784326
// 
// Dimensions of secrets
// s1: m1 = 269
// m: l = 0
// s2: m2 = 71
// 
// Size of secrets
// l2(s1) <= alpha = 27074.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 1)
// exact euclidean: yes (dimensions: [9, 19, 80, 80, 80], bounds: [7000.0, 6000.0, 6000.0, 6000.0, 24000.0])
// approximate infinity: yes (psi: 2556.1716, dimension: 21, bound: 43040.5)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 52009369.6, log(stdev1/1.55) = 25.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 3250585.6, log(stdev3/1.55) = 21.0
// stdev4 = 3250585.6, log(stdev4/1.55) = 21.0
// 
// Repetition rate
// M1 = 2.657125
// M2 = 3.018601
// M3 = 1.0117577
// M4 = 1.0299821
// total = 8.3584143
// 
// Security
// MSIS dimension: 18
// MSIS root hermite factor: 1.0043272
// MLWE dimension: 42
// MLWE root hermite factor: 1.004382
// 
// Proof size
// ~ 83.7460937500000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _merged_param_q_limbs[] = {1173UL, 8UL};
static const int_t _merged_param_q = {{(limb_t *)_merged_param_q_limbs, 2, 0}};
static const limb_t _merged_param_qminus1_limbs[] = {1172UL, 8UL};
static const int_t _merged_param_qminus1 = {{(limb_t *)_merged_param_qminus1_limbs, 2, 0}};
static const limb_t _merged_param_m_limbs[] = {319201044529UL, 0UL};
static const int_t _merged_param_m = {{(limb_t *)_merged_param_m_limbs, 2, 0}};
static const limb_t _merged_param_mby2_limbs[] = {159600522264UL, 0UL};
static const int_t _merged_param_mby2 = {{(limb_t *)_merged_param_mby2_limbs, 2, 0}};
static const limb_t _merged_param_gamma_limbs[] = {462322900UL, 0UL};
static const int_t _merged_param_gamma = {{(limb_t *)_merged_param_gamma_limbs, 2, 0}};
static const limb_t _merged_param_gammaby2_limbs[] = {231161450UL, 0UL};
static const int_t _merged_param_gammaby2 = {{(limb_t *)_merged_param_gammaby2_limbs, 2, 0}};
static const limb_t _merged_param_pow2D_limbs[] = {1048576UL, 0UL};
static const int_t _merged_param_pow2D = {{(limb_t *)_merged_param_pow2D_limbs, 2, 0}};
static const limb_t _merged_param_pow2Dby2_limbs[] = {524288UL, 0UL};
static const int_t _merged_param_pow2Dby2 = {{(limb_t *)_merged_param_pow2Dby2_limbs, 2, 0}};
static const limb_t _merged_param_Bsq_limbs[] = {14635861132901468233UL, 5UL, 0UL, 0UL};
static const int_t _merged_param_Bsq = {{(limb_t *)_merged_param_Bsq_limbs, 4, 0}};
static const limb_t _merged_param_scM1_limbs[] = {14715484656987845027UL, 12121817615619541768UL, 2UL};
static const int_t _merged_param_scM1 = {{(limb_t *)_merged_param_scM1_limbs, 3, 0}};
static const limb_t _merged_param_scM2_limbs[] = {3475190623207378560UL, 343128444396980339UL, 3UL};
static const int_t _merged_param_scM2 = {{(limb_t *)_merged_param_scM2_limbs, 3, 0}};
static const limb_t _merged_param_scM3_limbs[] = {17697069971185133941UL, 216890905988472839UL, 1UL};
static const int_t _merged_param_scM3 = {{(limb_t *)_merged_param_scM3_limbs, 3, 0}};
static const limb_t _merged_param_scM4_limbs[] = {4784049913985072743UL, 553071981796736113UL, 1UL};
static const int_t _merged_param_scM4 = {{(limb_t *)_merged_param_scM4_limbs, 3, 0}};
static const limb_t _merged_param_stdev1sq_limbs[] = {2704974526189404UL, 0UL, 0UL, 0UL};
static const int_t _merged_param_stdev1sq = {{(limb_t *)_merged_param_stdev1sq_limbs, 4, 0}};
static const limb_t _merged_param_stdev2sq_limbs[] = {40307261UL, 0UL, 0UL, 0UL};
static const int_t _merged_param_stdev2sq = {{(limb_t *)_merged_param_stdev2sq_limbs, 4, 0}};
static const limb_t _merged_param_stdev3sq_limbs[] = {10566306742927UL, 0UL, 0UL, 0UL};
static const int_t _merged_param_stdev3sq = {{(limb_t *)_merged_param_stdev3sq_limbs, 4, 0}};
static const limb_t _merged_param_stdev4sq_limbs[] = {10566306742927UL, 0UL, 0UL, 0UL};
static const int_t _merged_param_stdev4sq = {{(limb_t *)_merged_param_stdev4sq_limbs, 4, 0}};
static const limb_t _merged_param_inv2_limbs[] = {586UL, 4UL};
static const int_t _merged_param_inv2 = {{(limb_t *)_merged_param_inv2_limbs, 2, 1}};
static const limb_t _merged_param_inv4_limbs[] = {293UL, 2UL};
static const int_t _merged_param_inv4 = {{(limb_t *)_merged_param_inv4_limbs, 2, 1}};
static const unsigned int _merged_param_n[5] = {9, 19, 80, 80, 80};
static const limb_t _merged_param_Bz3sqr_limbs[] = {7275299485639021UL, 0UL, 0UL, 0UL};
static const int_t _merged_param_Bz3sqr = {{(limb_t *)_merged_param_Bz3sqr_limbs, 4, 0}};
static const limb_t _merged_param_Bz4_limbs[] = {52009369UL, 0UL};
static const int_t _merged_param_Bz4 = {{(limb_t *)_merged_param_Bz4_limbs, 2, 0}};
static const limb_t _merged_param_Pmodq_limbs[] = {15663227658401212038UL, 1UL};
static const int_t _merged_param_Pmodq = {{(limb_t *)_merged_param_Pmodq_limbs, 2, 0}};
static const limb_t _merged_param_l2Bsq0_limbs[] = {49000000UL, 0UL};
static const int_t _merged_param_l2Bsq0 = {{(limb_t *)_merged_param_l2Bsq0_limbs, 2, 0}};
static const limb_t _merged_param_l2Bsq1_limbs[] = {36000000UL, 0UL};
static const int_t _merged_param_l2Bsq1 = {{(limb_t *)_merged_param_l2Bsq1_limbs, 2, 0}};
static const limb_t _merged_param_l2Bsq2_limbs[] = {36000000UL, 0UL};
static const int_t _merged_param_l2Bsq2 = {{(limb_t *)_merged_param_l2Bsq2_limbs, 2, 0}};
static const limb_t _merged_param_l2Bsq3_limbs[] = {36000000UL, 0UL};
static const int_t _merged_param_l2Bsq3 = {{(limb_t *)_merged_param_l2Bsq3_limbs, 2, 0}};
static const limb_t _merged_param_l2Bsq4_limbs[] = {576000000UL, 0UL};
static const int_t _merged_param_l2Bsq4 = {{(limb_t *)_merged_param_l2Bsq4_limbs, 2, 0}};
static const limb_t _merged_param_Ppmodq_0_limbs[] = {8644669560717532671UL, 0UL};
static const int_t _merged_param_Ppmodq_0 = {{(limb_t *)_merged_param_Ppmodq_0_limbs, 2, 1}};
static const limb_t _merged_param_Ppmodq_1_limbs[] = {7635863244191013503UL, 0UL};
static const int_t _merged_param_Ppmodq_1 = {{(limb_t *)_merged_param_Ppmodq_1_limbs, 2, 1}};
static const limb_t _merged_param_Ppmodq_2_limbs[] = {5041789858829734271UL, 0UL};
static const int_t _merged_param_Ppmodq_2 = {{(limb_t *)_merged_param_Ppmodq_2_limbs, 2, 1}};
static const int_srcptr _merged_param_l2Bsq[] = {_merged_param_l2Bsq0, _merged_param_l2Bsq1, _merged_param_l2Bsq2, _merged_param_l2Bsq3, _merged_param_l2Bsq4};
static const int_srcptr _merged_param_Ppmodq[] = {_merged_param_Ppmodq_0, _merged_param_Ppmodq_1, _merged_param_Ppmodq_2};
static const polyring_t _merged_param_ring = {{_merged_param_q, 64, 68, 6, moduli_d64, 3, _merged_param_Pmodq, _merged_param_Ppmodq, _merged_param_inv2}};
static const dcompress_params_t _merged_param_dcomp = {{ _merged_param_q, _merged_param_qminus1, _merged_param_m, _merged_param_mby2, _merged_param_gamma, _merged_param_gammaby2, _merged_param_pow2D, _merged_param_pow2Dby2, 20, 1, 39 }};
static const abdlop_params_t _merged_param_tbox = {{ _merged_param_ring, _merged_param_dcomp, 274, 71, 0, 11, 18, _merged_param_Bsq, 1, 8, 5, 140, 1, 25, _merged_param_scM1, _merged_param_stdev1sq, 2, 12, _merged_param_scM2, _merged_param_stdev2sq}};
static const abdlop_params_t _merged_param_quad_eval_ = {{ _merged_param_ring, _merged_param_dcomp, 274, 71, 9, 2, 18, _merged_param_Bsq, 1, 8, 5, 140, 1, 25, _merged_param_scM1, _merged_param_stdev1sq, 2, 12, _merged_param_scM2, _merged_param_stdev2sq}};
static const abdlop_params_t _merged_param_quad_many_ = {{ _merged_param_ring, _merged_param_dcomp, 274, 71, 10, 1, 18, _merged_param_Bsq, 1, 8, 5, 140, 1, 25, _merged_param_scM1, _merged_param_stdev1sq, 2, 12, _merged_param_scM2, _merged_param_stdev2sq}};
static const lnp_quad_eval_params_t _merged_param_quad_eval = {{ _merged_param_quad_eval_, _merged_param_quad_many_, 2}};
static const lnp_tbox_params_t _merged_param = {{ _merged_param_tbox, _merged_param_quad_eval, 1, _merged_param_n, 21, 5, 274, 2, 21, _merged_param_scM3, _merged_param_stdev3sq, 2, 21, _merged_param_scM4, _merged_param_stdev4sq, _merged_param_Bz3sqr, _merged_param_Bz4, &_merged_param_l2Bsq[0], _merged_param_inv4, 85756UL }};

static const unsigned int merged_param_Ps[1] = {9};
static const unsigned int merged_param_Es0[9] = {0, 1, 2, 3, 4, 5, 6, 7, 8};
static const unsigned int merged_param_Es1[19] = {10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28};
static const unsigned int merged_param_Es2[80] = {29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108};
static const unsigned int merged_param_Es3[80] = {109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188};
static const unsigned int merged_param_Es4[80] = {189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268};
static const unsigned int *merged_param_Es[5] = { merged_param_Es0, merged_param_Es1, merged_param_Es2, merged_param_Es3, merged_param_Es4, };
static const unsigned int merged_param_Es_nrows[5] = {9, 19, 80, 80, 80};

static const limb_t merged_param_p_limbs[] = {274877906941UL};
static const int_t merged_param_p = {{(limb_t *)merged_param_p_limbs, 1, 0}};
static const limb_t merged_param_pinv_limbs[] = {1843829755136380882UL, 1UL};
static const int_t merged_param_pinv = {{(limb_t *)merged_param_pinv_limbs, 2, 0}};
static const unsigned int merged_param_s1_indices[269] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268};
static const lin_params_t merged_param = {{ _merged_param, 64, merged_param_p, merged_param_pinv, 1, merged_param_s1_indices, 269, NULL, 0,  merged_param_Ps, 1, merged_param_Es, merged_param_Es_nrows, NULL, NULL }};

